# Nodame configuration file
#
# Use {{ var.name }} to load previous configuration
#
# You can omit any configuration has default value
#
# Example:
#
#   [module.items.cool]
#   enable          = true
#   ajax            = true
#   xhr_only        = false
#   dev_only        = false
#   middleware      = false
#
# Can be set as follows:
#
#   [module.items.cool]

########################
# Server configuration #
########################
[server]

# Set maintenance mode
#
# default false
#
# maintenance     = false

# Set enable powered by
#
# default false
#
# powered_by      = false

# Set port to run
#
# default 3000
#
# port            = 3000

# Set non-development environment
#
# default ["production", "staging"]
#
# release_env     = ["production", "staging"]

# Set enforce secure connection on non-development environment
#
# default true
#
# enforce_secure  = true

# Set bootware, these modules will be loaded on boot
# Bootware modules need to be put in ./bootwares directory
#
# default []
#
# bootwares       = []

# Set to block favicon request
#
# default true
#
# block_favicon   = true

#############################
# Application configuration #
#############################
[app]

# Set application name
# alphanumeric, "~", "-", and "_" only
name            = "my-project"

# Set application title
# This will be shown in every title bar as in <title>
#
# Default "Nodame"
#
# title           = "Nodame"

# Set title separator
#
# default "|"
#
# title_separator = "|"

# Set application description
# This will be shown in meta description
#
# default "Nodame is a node.js framework built on express 4.0"
#
# desc            = "Nodame is a node.js framework built on express 4.0"

# Set debug name
debug_name      = "{{ app.name }}:server"


##########
# Cookie #
##########
[cookie]

# Set domain for your cookie
#
# default "localhost"
#
# domain          = "localhost"

# Set session key for your cookie
#
# default "_NODAME_"
#
# session         = "_NODAME_"


#####################
# URL configuration #
#####################

[url]

# Set hostname
#
# default "http://localhost:3000"
#
# hostname        = "http://localhost:3000"

# Set base url for your project
# This is your "home" url
base            = "{{ url.hostname }}/{{ app.name }}"

# Set assets url
assets          = "{{ url.hostname }}/assets"

# You can add additional url configuration below
# url_name      = "http://your.domain.com"


######################
# View configuration #
######################
[view]

# Default template (theme)
#
# default "default"
#
# template        = "default"

# Set to enable device capture
#
# default true
#
# device_capture  = true

# Set to enable serving mobile device in different view
# Only applies when device_capture is set true
#
# default false
#
# mobile          = false

# Set mobile view enforcing
#
# default false
# 
# enforce_mobile  = false

# Set enforce mobile type (only if enforce_mobile is set true)
# soft - desktop device will be served with mobile view
# hard - desktop device will be shown a page to use mobile device
#
# default soft
#
# enforce_mobile_type = "soft"

# Set view cache (only applies when cache enable is set true)
# Set whether to enable html cache
#
# default false
#
# cache           = false

# Set cache time in seconds (only if cache is set true)
#
# default 900
#
# cache_time    = 900

# Set 404 redirect
# When this set true, any 404 page will be redirected to default module
#
# default false
#
# redirect_404    = false


########################
# Assets configuration #
########################
[assets]

# Set true to enable static server
#
# default true
#
# enable_server   = true

# Set route to server your static server
# Only applies when enable_server is set true
#
# default '/assets'
#
# route           = '/assets'

# Set directory where the assets is stored
#
# default './assets'
#
# dir             = './assets'


################
# Localisation #
################
[locale]

# Set to enable Localisation
#
# default true
#
# enable          = true

# Set default language (only of locale is set enable)
# Any missing localisation will refer to this defaul language
#
# default "en"
#
# default         = "en"


#########
# Cache #
#########
[cache]

# Set to enable cache
#
# default false
#
# enable          = false

# Set cache client
#
# default "redis"
#
# client          = "redis"

    # Caches
    [cache.clients]

        # Redis configuration
        [cache.clients.redis]

            [cache.clients.redis.map]
            session         = ["shard_1"]
            html            = ["shard_1"]

            [cache.clients.redis.shard_1]
            master          = "127.0.0.1:6379"
            slave           = "127.0.0.1:6379"


###########
# Mailing #
###########
[email]

# Set to enable email service
#
# default false
#
# enable          = false

# Set sender address
sender_addr     = "your@email.com"

# Set sender name
sender_name     = "Sender Name"

# Set bcc address
bcc_addr        = "your@email.com"

# Set bcc name
bcc_name        = "BCC Name"

# Set E-mail client
#
# default "mandrill"
#
# client          = "mandrill"

    # Email clients
    [email.clients]

        # Mandril configuration
        [email.clients.mandrill]

        # Set mandrill key
        key    = "123456"


###############
# Secret Keys #
###############
[secret_key]

# Set session secret key
session         = "123456"

# Set user secret key
user            = "123456"


###########
# Session #
###########
[session]

# Set session url
url             = "{{ url.hostname }}"

# Set use token
#
# default false
#
# request_token   = false

# Set token module
# A parameter containing userid will be passed
# Module must return object with key and value
#   {
#       "key": "value"
#   }
#
# default "request_token"
#
# request_token_module = "request_token"


##########
# Logger #
##########
[logger]

# Set to enable logger
#
# default false
#
# enable          = false

    # Logger clients
    [logger.clients]

        # Morgan configuration
        [logger.clients.morgan]

        # Set to enable morgan
        #
        # enable true
        #
        # enable          = true

        # Syslog logger configuration

        [logger.clients.syslog]

        # Set to enable syslog
        #
        # default false
        #
        # enable          = false

        # Set defaul error log file location
        #
        # default "./logs/error.log"
        #
        # error_stream    = "./logs/error.log"

        # Set defaul access log file location
        #
        # default "./logs/access.log"
        #
        # access_stream   = "./logs/access.log"

        # Sentry configuration
        [logger.clients.sentry]

        # Set to enable sentry
        #
        # default false
        #
        # enable          = false

        # Set sentry dns
        dns             = "123456"

        # Email logger configuration
        # Only applies when "email" is set true
        [logger.clients.email]

        # Set to enable email logger
        #
        # default false
        #
        # enable          = false

        # Set recipient address
        recipient_addr  = "your@email.com"

        # Set recipient name
        recipient_name  = "Recipient Name"

        # Set sender addr
        sender_addr     = "your@email.com"

        # Set sender name
        sender_name     = "Sender Name"

        # Console logger configuration
        [logger.clients.console]

        # Set to enable console logger
        #
        # default true
        #
        # enable          = true


        [logger.clients.datadog]

        # Set to enable datadog
        #
        # default false
        #
        # enable          = false

        # Set host
        host            = "127.0.0.1"

        # Set port
        port            = "8125"

            # Set Keys
            [logger.clients.datadog.key]

            # Error counter
            error           = "errors.{{ app.name }}"


########################
# Module configuration #
########################
[module]

# Set default module
#
# default "home"
#
# default         = "home"

    # Module routes
    [module.items]

    # Home module configuration
    # [module.items.module_name]
    #
    # Set to enable module
    #
    # default true
    # enable          = true
    #
    # Set to enable ajax routes
    #
    # default true
    # ajax            = true
    #
    # Set to only accept xhr requests
    #
    # default false
    # xhr_only       = false
    #
    # Set to only available in develop environment
    #
    # default false
    # dev_only        = false
    #
    # Set to enable middleware
    # Middleware module needs to put in ./middleware
    #
    # default false
    # middleware      = false
    #
    ## Template ##
    #
    # [module.items.module_name]
    # enable        = true
    # ajax          = true
    # xhr_only      = false
    # dev_only      = false
    # Middleware    = false

        [module.items.home]

        [module.items.about]

######################
# Menu configuration #
######################
[menu]

# Set to enable automated menu
#
# default true
#
# enable          = true

# Set to enable font-icon
#
# default false
#
# font_icon       = false

# Set font icon class prefix (only if font_icon is set true)
#
# default "font-icon-"
#
# font_icon_class = "font-icon-"

    # Menu items
    [menu.items]

    ## Template ##
    # Menu items are sorted orderly
    # "menu_name" will be used in localisation as "LABEL_MENU_MENU_NAME"
    #
    #   [menu.items.menu_name]
    #
    #   # Set to enable menu item
    #   #
    #   # default true
    #   enable          = true
    #
    #   # Set menu url
    #   #
    #   # default "#"
    #   url             = "{{server.url.base}}/menu_name"
    #
    #   # Set font icon (only if font_icon is set true)
    #   #
    #   # default ""
    #   font_icon       = "menu_name"
    #
    #   # Set to be shown only in guest access
    #   #
    #   # default false
    #   guest_only      = false
    #
    #   # Set to be shown only in logged in access
    #   #
    #   # default false
    #   auth_only       = false
    #
    ## TEMPLATE ##
    # [menu.items.menu_name]
    # enable      = true
    # url         = "http://menu.url"
    # font_icon   = "menu-font-icon"
    # guest_only  = false
    # auth_only   = false

        [menu.items.home]
        url         = "{{ url.base }}/home"

        [menu.items.about]
        url         = "{{ url.base }}/about"

        [menu.items.wiki]
        url         = "https://github.com/tokopedia/nodame/wiki"
